### ISSUE TITLE
Suggesting new feature: to know if any event has been dropped.

### ISSUE THREAD

**Issue by jose3m** [serilog/serilog-sinks-async#13]
Hi.

I would like to suggest a new feature that would be very usefull (on my point of view). It consists in having a mechanism to know from outside the Serilog if the Async has dropped any event from last query until now (or if not possible then from starting execution).

 What do you think about it?

Thanks a lot.

**Comment by nblumhardt** [comment]
Hi Jose! The `SelfLog` feature of Serilog already provides this to some extent:

```csharp
SelfLog.Enable(s => /* Event was written */);
```

The message is this one: https://github.com/serilog/serilog-sinks-async/blob/dev/src/Serilog.Sinks.Async/Sinks/Async/BackgroundWorkerSink.cs#L35

How's that fit?

Cheers,
Nick

**Comment by jose3m** [comment]
Hi Nick !

The problem with SelfLog is that all SelfLog calls from all sinks are captured and using a text writer is not optimal (in my opinion).

What I mean is to have a mechanism only to know drops without interferences from other sinks. As, in example, injecting a class (interface) on the contructor with a function that is called any time an event has been dropped, then it is  responsability of the owner of the class (implemented interface) to treat that action (incrementing a counter, setting a bool variable, setting the DateTime for the last drop, etc...).

Thanks.
Jose

**Comment by nblumhardt** [comment]
Hi Jose, thanks for the follow-up.

The `SelfLog` no longer uses a `TextWriter` as of v2.0 - an `Action<string>` is now accepted instead.

I agree that matching on the message is not always optimal. If the code received a more actionable message, what action (in your scenario) would the handler be able to take?

Regards,
Nick

**Comment by jose3m** [comment]
Hi Nick.

Our initial target is to generate a kind of real time graph with the number of dropped events, so we have to record and store it. This will be used to set up the platform to minimize dropped events.

If you want I can make a PR so you can see what would be the change I propose.

Thank you very much for your time.

Jose

**Comment by nblumhardt** [comment]
Thank you for the clarification, that makes sense.

Although it's a reasonable feature, I'd rather hold off on it for now just to see what other kinds of requirements come up for this sink first. It's easy to end up with a lot of small features that individually make sense, but put together become cluttered.

To implement this today you can use:

```csharp
SelfLog.Enable(s => {
    if (s.StartsWith("Serilog.Sinks.Async.BackgroundWorkerSink unable to enqueue")
    {
        // Increment the counter
    }
});
```

There shouldn't be too much wasted work, as the `SelfLog` is only ever used when errors/unusual situations occur.

I think it's an interesting scenario though. There have been some discussions in the past about adding an integration point to Serilog for performance counter-type measurements. This would provide higher-level events, for example `BackgroundWorkerSink.OverCapacityEventDropped`, that could be subscribed to globally to cover this scenario.

If you're interested in exploring that avenue further, we could open a ticket in `serilog/serilog` to discuss?

Regards,
Nick
