### ISSUE TITLE
Using this with .NET Core

### ISSUE THREAD

**Issue by YodasMyDad** [serilog/serilog-sinks-async#16]
I have added your rolling log to .NET core from reading your blog post

`loggerFactory.AddFile("Logs/myapp-{Date}.txt");`

I'd like to use this async package? I'm guessing I can't use AddFile() now if I want it to be async?

**Comment by nblumhardt** [comment]
Howdy! `AddFile()` already bundles `Async()` behind the scenes:

https://github.com/serilog/serilog-extensions-logging-file/blob/dev/src/Serilog.Extensions.Logging.File/Microsoft/Extensions/Logging/FileLoggerExtensions.cs#L129

👍 Cheers!
