### ISSUE TITLE
Make BackgroundWorkerSink public and not sealed

### ISSUE THREAD

**Issue by DixonDs** [serilog/serilog-sinks-async#18]
It would make it possible to use it as a decorator in other packages. In my particular case, I would use it to decorate the current implementation of MicrosoftTeamsSink (https://github.com/DixonDs/serilog-sinks-teams/blob/71d1edc1e3fb163741c4b9e330b18a71c66e0511/src/Serilog.Sinks.MicrosoftTeams/Sinks/MicrosoftTeams/MicrosoftTeamsSink.cs)

**Comment by nblumhardt** [comment]
Thanks for the note!

I'm not sure the interface to `BackgroundWorkerSink` is stable enough to be part of the public API at this point. Since it's only ~20 significant lines of code, is copying it (or the basic structure of it) into the Teams sink project an option?

**Comment by DixonDs** [comment]
In result, similar functionality was implemented via periodic batching sink (https://github.com/DixonDs/serilog-sinks-teams/pull/2). Shall I close this issue or is it still useful to be open?

**Comment by nblumhardt** [comment]
Thanks for the pointer - will keep an eye on it 👍
