### ISSUE TITLE
Feature idea: strategy for when the queue is full

### ISSUE THREAD

**Issue by cocowalla** [serilog/serilog-sinks-async#20]
At present, the `BackgroundWorkerSink` will drop messages when the queue is full. It would be good to be able to configure this behaviour so there is an option to _block_ instead of drop.

**Comment by nblumhardt** [comment]
I think this would be a great addition to the sink. It should be enough to represent it with a `bool` and switch behavior in `Emit()`.

I'm not likely to pick this up in the short term, but can help with a PR if anyone decides to take it on.

**Comment by cocowalla** [comment]
@nblumhardt I'll have a crack at this one

**Comment by cocowalla** [comment]
@nblumhardt I submitted PR #21 for this

**Comment by bartelink** [comment]
@cocowalla I'm going to go out on a limb and declare this Done Done ;)
