### ISSUE TITLE
How to use it with .net core appsettings.json file

### ISSUE THREAD

**Issue by rushi216** [serilog/serilog-sinks-async#22]
How can we use it with .net core appsettings.json file (https://github.com/serilog/serilog-settings-configuration)?

**Comment by Ricky-G** [comment]
you would configure it like it this (the below example is using a rolling log file)

"WriteTo": [{
      "Name": "Async",
      "Args": {
        "configure": [{
          "Name": "RollingFile",
          "Args": {
            "pathFormat": "Logs/log-{Date}.txt",
            "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
            "fileSizeLimitBytes": 5000000,
            "retainedFileCountLimit": null
          }
        }]
      }
    }],

**Comment by frg** [comment]
Thanks @Ricky-G! Looks like this issue can be closed.
