### ISSUE TITLE
XML configuration support

### ISSUE THREAD

**Issue by emrahcetiner** [serilog/serilog-sinks-async#25]
Is there a plan for this feature?

**Comment by nblumhardt** [comment]
Hi! There's no work-in-progress on this; the main issue is that we haven't come up with a syntax that we like - suggestions for how this would look are welcome. Thanks!

**Comment by emrahcetiner** [comment]
this would look great for me:

```
<add key="serilog:using:Async" value="Serilog.Sinks.Async" />
<add key="serilog:write-to:Async:using:File" value="Serilog.Sinks.File" />
<add key="serilog:write-to:Async.bufferSize" value="1000" />

<add key="serilog:write-to:Async:File.path" value="..." />
<add key="serilog:write-to:Async:File.rollOnFileSizeLimit" value="true" />
<add key="serilog:write-to:Async:File.rollingInterval" value="Day" />
...
```

**Comment by nblumhardt** [comment]
Thanks for the suggestion 👍

**Comment by pjduerden** [comment]
Any further update on if/when this would be available for use?

**Comment by nblumhardt** [comment]
Here's a slight tweak:

```xml
<!-- No need to nest the `using` directive for `File` -->
<add key="serilog:using:Async" value="Serilog.Sinks.Async" />
<add key="serilog:using:File" value="Serilog.Sinks.File" />

<add key="serilog:write-to:Async.bufferSize" value="1000" />

<!-- Configure is an `Action<LoggerSinkConfiguration>`; this is what `write-to` effectively
        applies to, so by including the parameter name and dropping back into sink configuration
        is a mechanism we could carry through to other `Action<T>` arguments -->
<add key="serilog:write-to:Async.configure:File.path" value="..." />
<add key="serilog:write-to:Async.configure:File.rollOnFileSizeLimit" value="true" />
<add key="serilog:write-to:Async.configure:File.rollingInterval" value="Day" />
...
```

Trying to take a more regular approach to how parameters are matched/provided will make it easier to add reliable support to Serilog Analyzer.

The next step for this one is to create an issue in serilog/serilog, where the code for this feature would live. If there's support, and someone is able to send a strong PR, I don't think anything would prevent this going into a 2.6.1.

**Comment by nblumhardt** [comment]
We're now tracking this in: https://github.com/serilog/serilog/issues/1072

**Comment by mishrapw** [comment]
@nblumhardt 
Hi,
Do we have XML configuration support in latest Async sink ? 
Not able to figure out with above chain responses.

**Comment by nblumhardt** [comment]
Hi @mishrapw - no, the issue linked in my comment one above yours is tracking progress. Cheers!
