### ISSUE TITLE
Serilog Async not working when confiuged in appsetting.json core 2.0

### ISSUE THREAD

**Issue by fouadroumieh** [serilog/serilog-sinks-async#26]
I'm configuring the Async mode via the Serilog section of appsettings.json, but its not working and no logs get written to the file. Its a web api .net core 2.0 project and this is how my config looks like:
`"Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
          "pathFormat": "logs//api-logs-{Date}.txt",
          "fileSizeLimitBytes": "100000000",
          "rollOnFileSizeLimit": true
        }
      }
    ]
  }`

If I configure from the code it works:
` Log.Logger = new LoggerConfiguration()
.WriteTo.Async(a => a.RollingFile("logs//api-logs-{Date}.txt"))
                .ReadFrom.Configuration(Configuration)
                .CreateLogger();`

**Comment by fouadroumieh** [comment]
anyone here?

**Comment by tsimbalar** [comment]
Reindenting your code to make it readable by a human being :)

```json
{
  "Serilog": { 
    "MinimumLevel": "Debug", 
    "WriteTo": [ 
      { 
        "Name": "Async", 
        "Args": { 
            "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact", 
            "pathFormat": "logs//api-logs-{Date}.txt", 
            "fileSizeLimitBytes": "100000000", 
            "rollOnFileSizeLimit": true 
          }
        } 
      ] 
    }
}
```

Comparing with [what is documented ](https://github.com/serilog/serilog-sinks-async/blob/dev/README.md): 

```json
{
  "Serilog": {
    "WriteTo": [{
      "Name": "Async",
      "Args": {
        "configure": [{
          "Name": "LiterateConsole"
        }]
      }
    }]
  }
}
```

I believe there is one level missing in your configuration and it shoud look something like this : 

```json
```json
{
  "Serilog": {
    "WriteTo": [{
      "Name": "Async",
      "Args": {
        "configure": [{
          "Name": "RollingFile", 
          "Args": { 
            "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact", 
            "pathFormat": "logs//api-logs-{Date}.txt", 
            "fileSizeLimitBytes": "100000000", 
            "rollOnFileSizeLimit": true 
          }
        }]
      }
    }]
  }
}
```


I hope that helps ...

**Comment by fouadroumieh** [comment]
Yep that works, thank you. There should be some exception around this, same as when there is a missing attribute in the section.
