### ISSUE TITLE
Make wiki writable for any user

### ISSUE THREAD

**Issue by MNF** [serilog/serilog-sinks-async#27]
Could you please make Wiki writable for any user as it’s done in other repositories such as https://github.com/serilog/serilog-sinks-eventlog/wiki and https://github.com/serilog/serilog-settings-configuration/wiki.
It will allow community to easily provide additional information, such as examples of configuration.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! Perhaps PRs for the README would be sufficient? We don't really have plans to flesh out and maintain a wiki here for this sink.

**Comment by MNF** [comment]
Community supported **wiki** provides different ways to describe the features, than official documentation such as README. Raising issues or PRs  for some minor changes/additions in documentations is a relatively long process, that requires more time spent by requestors and owners. 

Having **wiki** is the easiest process for contributors and doesn't required any effort for owners. At the same time you (and anyone else) always able to change/delete any incorrect information.

Wiki is supposed to be maintained by community, not by authors of the project, it doesn't expect formal review process. Wikipedia and StackOverflow rely on community to maintain content and fix what is wrong. It is not an official documentation and you don't need to spend your valuable time to review content.

You have a good documentation/Readme, but some information can be presented from the different angle or in a different style, that may be not suitable for the official documentation.  Wiki is very easy to contribute, submit documentation pull request is more annoying process, and many people will not do it. Wiki can give your users  additional  information without any effort from you.


If you have concerns about the quality of the information, add to  wiki home page link to relevant official documentation ( and note that wiki pages are not endorsed by the owners of the project and maintained by community.

**Comment by nblumhardt** [comment]
Okay, let's give it a shot 👍 - editing should be open, now.
