### ISSUE TITLE
Failing Integration tests

### ISSUE THREAD

**Issue by jezzsantos** [serilog/serilog-sinks-async#3]
We have some failing integration tests. 
Tests demonstrate that we are receiving more log events than we send, in some of the tests.

Not sure why this is happening yet, as we reset all the instances we are using. 

Perhaps the sink instance needs to be disposed (needs to be `IDisposable`)?

**Comment by nblumhardt** [comment]
Howdy :-) ... I haven't had a chance to clone/run this yet, but should have a chance soon. I think the disposal behaviour of the sink will turn out to be pretty important anyway, so perhaps that is a good place to start?

(`PeriodicBatchingSink` attempts to flush itself completely on dispose, but once the process starts it does not accept any new events. So far these semantics have worked pretty well.)

**Comment by jezzsantos** [comment]
thanks @nblumhardt, perhaps we should try to kill both this issue and #4 as you suggested by changing to Ilogger and make it disposable?
Could you show us how?

**Comment by jezzsantos** [comment]
@nblumhardt are you able to show me how to convert this sink into the sink you have been suggesting? that may help resolve the problems we are seeing in testing?

**Comment by nblumhardt** [comment]
Sounds like a plan, just left a comment to that effect in #8. May take a few days with what I have on my plate, but I'll see what kind of PR I can pull together. Thanks @jezzsantos !

**Comment by nblumhardt** [comment]
`AsyncWorkerSink` should handle disposal correctly, need to verify it passes the suite in #10 anyway so will cover this over there.
