### ISSUE TITLE
Async logging for Subloggers

### ISSUE THREAD

**Issue by avish0694** [serilog/serilog-sinks-async#36]
Is there any way to use serilog-sinks-async with subloggers?
Here is my implementation of Serilog Logger In EventStore--> https://github.com/EventStore/EventStore/pull/1651
Here is how I have configured serilog: 
` Serilog.Log.Logger =
                 new Serilog.LoggerConfiguration()
                 .MinimumLevel.Verbose()
                 .WriteTo.Logger( lc => lc.ReadFrom.AppSettings("std",configFilePath))
                 .WriteTo.Logger( lc => lc.ReadFrom.AppSettings("error",configFilePath))
                 .WriteTo.Logger( lc => lc.ReadFrom.AppSettings("stats",configFilePath))
                 .CreateLogger();
                 Serilog.Debugging.SelfLog.Enable(Console.Error);`

**Comment by nblumhardt** [comment]
Hi Avish! Yes, it should be something like:

```csharp
Serilog.Log.Logger = new Serilog.LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.Async(wt => wt.Logger( lc => lc.ReadFrom.AppSettings("std",configFilePath)))
    // <snip>
    .CreateLogger(); 
```

How does this go for you?

**Comment by avish0694** [comment]
Yes it works! Thank you so much @
We can close this issue now.
