### ISSUE TITLE
File Version in 1.3.0 Release Incorrect

### ISSUE THREAD

**Issue by jimmyiv** [serilog/serilog-sinks-async#37]
Serilog.Sinks.Async.dll 1.1.0 has a FileVersion of 1.1.0.  Recently upgrading to 1.3.0 and the Serilog.Sinks.Async.dll has a FileVersion of 1.0.0.  I would expect the FileVersion to be 1.3.0 or at least greater than one of the previous versions. The FileVersion instead has gone backwards.  This causes issues with some installer technologies.

**Comment by nblumhardt** [comment]
Thanks for the report, not sure what went wrong in the here, but I know firsthand how annoying that MSI behavior is! Help tracking this down appreciated, if anyone can pick this up.
