### ISSUE TITLE
Design change: IlogEventSink.Emit() to ILogger.Write()

### ISSUE THREAD

**Issue by jezzsantos** [serilog/serilog-sinks-async#4]
from @nblumhardt, over at https://github.com/serilog/serilog/issues/809
---
@jezzsantos I haven't thought this through entirely, and Logger implements ILogEventSink explicitly so it may be better for the BufferedQueueSink to accept a Logger directly (and call Write() rather than Emit()).

Accepting Logger would also make it clearer that `BufferedQueueSink` needs to be `IDisposable` and dispose the logger at that point.

Hope this gets the ball rolling, anyway!

**Comment by nblumhardt** [comment]
Will re-validate this while paring things back in https://github.com/serilog/serilog-sinks-async/issues/10
