### ISSUE TITLE
Preventing Memory Leaks

### ISSUE THREAD

**Issue by jezzsantos** [serilog/serilog-sinks-async#42]
I am tracking down a memory leak which I am experiencing in code using this sink.
I am not definitively saying that this sink is causing it, I am more trying to understand whether this sink is.
Perhaps someone can help me identify the issue?

A memory dump reveals that I have about 100 threads sitting waiting on the call `System.Threading.Monitor.Wait()`, which is called by `Serilog.Sinks.Async.BackgroundWorkerSink.Pump` with a call stack like this:

```
ntdll!ZwWaitForMultipleObjects+c
--
KERNELBASE!WaitForMultipleObjectsEx+f0
clr!WaitForMultipleObjectsEx_SO_TOLERANT+3c
clr!Thread::DoAppropriateWaitWorker+237
clr!Thread::DoAppropriateWait+64
clr!CLREventBase::WaitEx+128
clr!CLREventBase::Wait+1a
clr!Thread::Block+25
clr!SyncBlock::Wait+189
clr!ObjectNative::WaitTimeout+cb
mscorlib_ni!System.Threading.Monitor.Wait(System.Object, Int32, Boolean)+17
mscorlib_ni!System.Threading.Monitor.Wait(System.Object, Int32, Boolean)+17
mscorlib_ni!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32, UInt32, System.Threading.CancellationToken)+4b
mscorlib_ni!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32, UInt32, System.Threading.CancellationToken)+4b
mscorlib_ni!System.Threading.SemaphoreSlim.Wait(Int32, System.Threading.CancellationToken)+1f0
mscorlib_ni!System.Threading.SemaphoreSlim.Wait(Int32, System.Threading.CancellationToken)+1f0
System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib]].TryTakeWithNoTimeValidation(System.__Canon ByRef, Int32, System.Threading.CancellationToken, System.Threading.CancellationTokenSource)+eb
System.Collections.Concurrent.BlockingCollection`1+<GetConsumingEnumerable>d__68[[System.__Canon, mscorlib]].MoveNext()+a2
Serilog.Sinks.Async.BackgroundWorkerSink.Pump()+64
clr!ThreadStaticHandleTable::AllocateHandles+4c
mscorlib_ni!System.Threading.Tasks.Task.InnerInvoke()+28
mscorlib_ni!System.Threading.Tasks.Task.Execute()+30
mscorlib_ni!System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)+1a
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+e5
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+16
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+16
mscorlib_ni!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+d8
mscorlib_ni!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+d8
mscorlib_ni!System.Threading.Tasks.Task.ExecuteEntry(Boolean)+b2
mscorlib_ni!System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(System.Object)+1c
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart_Context(System.Object)+73
mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+e5
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+16
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+16
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+41
mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+41
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart(System.Object)+4e
mscorlib_ni!System.Threading.ThreadHelper.ThreadStart(System.Object)+4e
clr!CallDescrWorkerInternal+34
clr!CallDescrWorkerWithHandler+6b
clr!MethodDescCallSite::CallTargetWorker+16a
clr!ThreadNative::KickOffThread_Worker+173
clr!ManagedThreadBase_DispatchInner+71
clr!ManagedThreadBase_DispatchMiddle+7e
clr!ManagedThreadBase_DispatchOuter+5b
clr!ManagedThreadBase_DispatchInCorrectAD+15
clr!Thread::DoADCallBack+328
clr!ManagedThreadBase_DispatchInner+4e
clr!ManagedThreadBase_DispatchMiddle+7e
clr!ManagedThreadBase_DispatchOuter+5b
clr!ManagedThreadBase_FullTransitionWithAD+2f
clr!ThreadNative::KickOffThread+256
clr!Thread::intermediateThreadProc+55
kernel32!BaseThreadInitThunk+24
ntdll!__RtlUserThreadStart+2f
ntdll!_RtlUserThreadStart+1b
```

![image](https://user-images.githubusercontent.com/3137590/51946866-cf61f880-2487-11e9-88e7-3c51fa7f9976.png)

**Comment by jezzsantos** [comment]
I am creating a new `LoggerConfiguration` object for every single ASP.NET request inside a type that implements `IDisposable`. and I believe my web framework is disposing of the dependency at the end of the request pipeline.

```
            this.logger = new LoggerConfiguration()
                .Enrich.With(new BlackListedPropertyRemover())
                .Enrich.FromLogContext()
                .WriteTo.Async(x => x.Sink(MySink), bufferSize)
                .MinimumLevel.Information()
                .CreateLogger();
```

I am missing something?

**Comment by jezzsantos** [comment]
Hey @nblumhardt,

Thanks. you've forced me to qualify my assertion how the IOC works. I will investigate that again to be sure.

**Comment by jezzsantos** [comment]
This clarification discussion makes me feel like I have nothing else to do to guard against potential IOC leaks: https://forums.servicestack.net/t/ioc-disposal-of-transient-dependencies/6876 
as far as cleaning up disposable instances.

Which is actually diossapointing, since I don't know what my next move is, now.

**Comment by jezzsantos** [comment]
Good challenge @bartelink, its helped me move along a resolution.

Your comment about only having a single `LoggerConfiguration` has sparked a new line of  enquiry for me. I am not very experienced using Serilog in many different environments, so having some guidance here would help me decide what direction to move in.

We never call `Log.Logger = new LoggerConfiguration()`.

Instead we have 5 `LoggerConfiguration` instances (in a single AppDoman) each with its own sink. There are 5 because we separate logging into: tracing, audits, crashes, alerts, counters, and then each of these are delivered into their own queue (by a separate sink), then shipped to persistent storage out of band. 

Each `LoggerConfiguration` we have, is instantiated by its own enclosing type, which are then registered in our IO. Then at runtime, the IOC injects the instance into our own Logger class. I looks something like this visually:

Our logger class (simplified):
```
public class Logger : IDisposable
{
    public ICrashManager CrashManager { get; set; }
    public IAuditManager AuditManager { get; set; }
    public IAlertManager AlertManager { get; set; }
    public ICounterManager CounterManager { get; set; }
    public ITraceManager TraceManager { get; set; }

    public void Crash(Crashlevel level, string message, Exception ex)
    {
        CrashManager.Crash(level, message, ex);
    }

    public void Trace(TraceLevel level, string source, string message)
    {
        TraceManager.Crash(level, source, message);
    }
    .... etc, etc

    public void Dispose()
    {
        ((IDisposable)CrashManager)?.Dispose();
        ... etc, etc
    }
}
```
And an implementation of one of those managers would look typically something like this:

```
public class CrashManager : ICrashManager, IDisposable
{
    private ILogger logger;

    public CrashManager()
    {
        var sink = new QueueSink("crashes");
        this.logger = new LoggerConfiguration()
                .Enrich.With(new BlackListedPropertyRemover())
                .Enrich.FromLogContext()
                .WriteTo.Async(x => x.Sink(sink), bufferSize)
                .MinimumLevel.Information()
                .CreateLogger();
    }

    public void Crash(CrashLevel level, string message, Exception ex)
    {
        using (LogContext.PushProperty("CorrelationId", CorrelationId))
        {
             using (LogContext.PushProperty("Message", message))
             {
                   this.logger.Write(ToSerilogLogLevel(level), ex, "{@Message}", ex.Message);
             }
        }
    }

    public void Dispose()
    {
        (this.logger as IDisposable)?.Dispose();
    }
}
```
So that the pattern we are using. 
The `Logger', `CrashManager`, `AuditManager` etc are all registered in our IOC as 'Transient' and instantiated every HTTP request, and supposedly then disposed at the end of the HTTP request.

So that means that our `LoggerConfiguration` instances should also be disposed every HTTP request.

With this in play I am wondering if you see any obvious mis-uses of Serilog in this pattern? and perhaps you could share you views on how it could be better applied.

**Comment by bartelink** [comment]
I'll let it percolate - first instinct is that there's no reason not to make 5 named logger instances and then pass out a contextual one to each transient manager 
```
// startup
CrashManager.TheLogger = ... CreateLogger();
// per request
new CrashManager(TheLogger..ForContext("requestId",Request.Id).ForContext<CrashManager>())
```
while they go to the same sink, the ForContext controls properties it carries (and the `SourceContext` one)

Note the `.ForContext<CrashManager>()` can also go once on the initial setup either.

**Comment by jezzsantos** [comment]
Thanks @bartelink,

I am not familiar with the syntax: `ForContext<CrashManager>()`, so I am not really folowing your explanation.

I do have one issue, which I should point out, that is not immediately apparent in my code example.

Each HTTP request I receive yields a separate set of connectionstrings (multi-tenancy) which means I cannot have any static variables between requests. My sinks use the connection strings.

**Comment by bartelink** [comment]
ForContext is kinda like LogManager.For<T> - it makes a scoped logger with the "class name" set to T. In Serilog, the 'source' is just a propery entitled 'SourceContext' that goes in the Dictionary of Properties in the LogEvent. There are also overloads that let you put in arbitrary key/value pairs for inclusion in the LogEvent. The resulting ILogger that ForContext yields is contextualized with this extra info - i.e. the very first one knows the sinks and level, then a ForContext can layer on the class, another cna layer on the tenant etc.

I can see how having connection strings per request might force the issue alright. One way of propagating info (like a connection string name) through to the sink from the running thread may be via the `LogContext` (there's decent docs for that) - then you can implement a Sink that forwards to a relevant pre-prepared or cached Logger based on what tenant you marked it as originating from.

Though obviously putting sensitive items in there is dangerous, even if you postprocess them to remove such properties.

While this may not sound much cleaner either, I'd be pretty confident that spinning up a log pipeline per request is not going to land you in a happy place either.

**Comment by nblumhardt** [comment]
How did this pan out, @jezzsantos ? I think a few months have passed, I'll close this as stale but if you think there's a bug here, please give the word :-)
