### ISSUE TITLE
BackgroundWorkerSink crashes if target sink throws an exception

### ISSUE THREAD

**Issue by silviucotilici** [serilog/serilog-sinks-async#44]
Hello guys, 

I am having the following setup: I am using _async-sink_ that targets _azuretablestorage-sink_. All nice and good until _azuretablestorage_ starts throwing some timeout exceptions (for whatever reasons). 

The thing is that when a timeout occurs (or any other exception) in the target sink,
the entire worker thread crashes (`BackgroundWorkerSink.Pump()`) and events from the queue are no longer dequeued and emitted trough the pipeline, so the queue quickly reaches max capacity and then drops out incoming events. Basically all logging mechanism is dead because of a single timeout.

I was wondering if wouldn't be nice to catch exceptions from the target sink and write them to selflog and let the worker thread continue pumping the rest of the events in the queue?
Eventually failed events could be stored and retried later.
Or exceptions like this should be treated in the target sink? what do you think?

**Comment by nblumhardt** [comment]
Thanks for the report. This is a regression introduced in #19, I'll PR a fix.
