### ISSUE TITLE
What is correct configuration in appsettings.json?

### ISSUE THREAD

**Issue by ziga34** [serilog/serilog-sinks-async#48]
Hello,

It's tough for me to figure it out, so please let me know what is the correct config:
```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Async" ], <--- Is it ok, or should be Serilog.Sinks.RollingFileAlternate?
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "bufferSize": 100000, <-- does this belongs here? Or elsewhere?
          "blockWhenFull": true, <-- does this belongs here? Or elsewhere?
          "configure": [
            {
              "Name": "RollingFileAlternate",
              "Args": {
                "logDirectory": "D:\\log",
                "fileSizeLimitBytes": 1048576,
                "outputTemplate": "[{Timestamp:o} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
              }
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by lonix1** [comment]
ensure you install the nuget `Serilog.Sinks.Async`

example: async sink that wraps file sink:

````json
{
  "Name": "Async",
  "Args": {
    "configure": [
      {
        "Name": "File",
        "Args": {
          "path": "logs/app.log",
          "rollingInterval": "Day",
          "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"
        }
      }
    ]
  }
}
````

The [docs for this](https://github.com/serilog/serilog-sinks-async#xml-appsettings-and-json-configuration) are unclear, they should be updated with a proper example like above.

**Comment by bartelink** [comment]
@ionix Your suggestion looks good - [Async over a console log is also debatable](https://stackoverflow.com/questions/53933661/does-serilog-sinks-console-sink-get-any-benefits-from-wrapping-to-serilog-sinks) If you cab make the time to do a PR based on the above it'd be great.

(Also your other issue pretty much duplicates the questions asked within this, no?)

**Comment by raheinz57** [comment]
The monitor implementation can be configured using a Serilog hook in appsettings.json. I have uploaded an implementation that loads the monitor via appsettings.json
