### ISSUE TITLE
Xamarin Support ?

### ISSUE THREAD

**Issue by mishrapw** [serilog/serilog-sinks-async#49]
It does not work in Xamarin.

**Comment by mishrapw** [comment]
@nblumhardt
Hi, Does it support in Xamarin ?

**Comment by nblumhardt** [comment]
I don't use Xamarin; if it fails, you may find some clues in `SelfLog` (see the Debugging and Diagnostics wiki page for details). Fixes and/or detailed issue descriptions would be welcome, but we don't have any current "Xamain Taskforce" to look into this ourselves.

**Comment by mishrapw** [comment]
@nblumhardt ; thanks for your response. It works, the issue was in target File Sink.
