### ISSUE TITLE
support for net472

### ISSUE THREAD

**Issue by Doug-R** [serilog/serilog-sinks-async#51]
Are there any plans to support net472 ?

**Comment by bartelink** [comment]
it supports net461 and netstandard2.0 - given net472 has good support for both, do you know of a specific advantage that would bring?

**Comment by Doug-R** [comment]
sorry, I was confused by this error   NU1202 Package Serilog.Sinks.Async 1.4.0 is not compatible with net472 (.NETFramework,Version=v4.2.)

![image](https://user-images.githubusercontent.com/2792675/69660570-3cadce00-1046-11ea-8bbc-76206056e8fc.png)

Solution was to Clear All NuGet Cache(s) in VS2019 Tools-Options-NuGet Package Manager-General
![image](https://user-images.githubusercontent.com/2792675/69660793-b1810800-1046-11ea-93a6-aa3b75bb7981.png)
