### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by tech7857** [serilog/serilog-sinks-async#52]
Hi

We implemented serilog async rollingfile sink in our MVC application. Somehow sometimes serilog is making the application crash by generating enormous threads making system go out of memory. Can you please suggest what could be the problem. We are pretty new to this. Thanks

![D4C944FB-370E-44D4-A6FC-2CEBC4D2A8B2](https://user-images.githubusercontent.com/33102270/70201471-c879c700-16e4-11ea-82fe-7d5bc6c3c932.png)

**Comment by nblumhardt** [comment]
Hi! Looks like you might be creating multiple root loggers (maybe one per request)? The Serilog `Logger` should be effectively singleton. Let me know if this helps 👍

**Comment by Abby86** [comment]
Hey Nick

Thanks for the reply. Yes previously we were initiating the logger property
on every request but now we have implemented the singleton. However do you
have any other recommendations on serilog implementation. What all
properties we need to consider. As me ntioned we are using rollingfile
async sink.

**Comment by nblumhardt** [comment]
Great! Glad to help.

I've written a bunch over the years at https://nblumhardt.com/ - the ASP.NET (Core) articles may be worth checking out, and the [Structured logging concepts in .NET Series](https://nblumhardt.com/2016/06/structured-logging-concepts-in-net-series-1/) remains relevant to what we're doing today.

Cheers,
Nick

**Comment by tech7857** [comment]
This is resolved
