### ISSUE TITLE
Use with MultiThreaded Xamarin Forms

### ISSUE THREAD

**Issue by cesar-moya** [serilog/serilog-sinks-async#53]
Is it safe to use on a MultiThreaded Xamarin Forms application writing to a file?

**Comment by nblumhardt** [comment]
If it runs, that's as much as we know (no one on the maintenance team currently works on anything targeting Xamarin, that I'm aware of). There haven't been any reported issues AFAIK. If you hit any issues, reports are welcome, and we'd aim to fix them (or be open to accepting fixes). HTH.
