### ISSUE TITLE
There is no WriteTo.Async even I have install this package in my WPF app with .net core 3.1 framework

### ISSUE THREAD

**Issue by arga1234** [serilog/serilog-sinks-async#54]
Here I try to using WriteTo.Async(), but why there is no Async() method after  WriteTo. When I try to write the Async() it will give me error like this _'LoggerSinkConfiguration' doest not contain a definition for 'Async' and no accessible method 'Async' accepting a first argument of type 'LoggerSinkConfiguration' could be found (are you missing some directive or an assembly reference ?)_  , how can I resolve this ?

**Comment by bartelink** [comment]
Best to ask on Stackoverflow with sample code and the full error message for a quick response. This package has [5000 downloads per day](https://www.nuget.org/packages/Serilog.Sinks.Async/) successful users, so the chances are its more likely to be an issue in the config of your project than a problem with the package. Have you done a `using Serilog` ?

**Comment by arga1234** [comment]
it is caused by my internal projects, I will close this

**Comment by vanusquarm** [comment]
What's the solution?

**Comment by NickByrnes** [comment]
> What's the solution?

I'm dealing with the same issue, I'm fairly confident that the solution is to be arga1234
