### ISSUE TITLE
Update readme file documentation

### ISSUE THREAD

**Issue by thiagograndesso** [serilog/serilog-sinks-async#55]
The section **Health Monitoring via the Monitor and Inspector interfaces** references the deprecated property `IAsyncLogEventSinkInspector.BoundedCapacity` instead of `IAsyncLogEventSinkInspector.BufferSize` specifically in the method `ExecuteAsyncBufferCheck`.

Is this something you'd like to update?

**Comment by nblumhardt** [comment]
Thanks! I believe so 👍
