### ISSUE TITLE
Sinks do not work if wrapped in Async Sink

### ISSUE THREAD

**Issue by Pcardoso89** [serilog/serilog-sinks-async#59]
I have been trying to test the Async sink to see if it would benefit the performance of an Application that I have to maintain, however I have not been able to get it to work by any method, neither json config or by initializing the class itself.

If I remove the Asyn() Method and simply create the Logger by using .WriteTo.File(), without changing any of the config values, then  the Logger will successfully write to the specified Local File and use all the previously set config Values. The same happens when I try to wrap the Console Sink, as I initially though this may be File Sink specific.

No exceptions are thrown, the Logger simply does not work.

Could I please have some assistance / guidance to understand if this is an issue with my current implementation or an actual issue?

So far,  have tried the following methods:

- 1: Reading the Config values directly from a Json config file, as specified in the documentation for this Sink and also in the Serilogs Sink Config documentation examples:

        `public static Logger InitializeLogger()
        {
            var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("config\\SerilogConfig.json")
                .Build();

            var logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();

            return logger;
        }`

Json Config:

`{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Async", "Serilog.Sinks.File", "Serilog.Sinks.Console" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "File",
              "Args": {
                "pathFormat": "Logs/log_.txt",
                "fileSizeLimitBytes": 5000000,
                "retainedFileCountLimit": 30
              }
            }
          ]
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId", "WithProcessId", "WithCorrelationId" ]
  }
}`

- 2: Initializing the Logger and setting the config values during initialization (without recourse to a Json config file to make sure the values are picked up correctly):

I read the config values from a custom Json file, and then parse them 1 by 1 when creating the Logger. Again this method works fine as soon as I remove the Async property.

Json file:

`{
  "Path": "Logs\\DiagnosticLog_.txt",
  "MinimumLevel": "Debug",
  "Enrichers": "FromLogContext, WithMachineName, WithThreadId, WithProcessId",
  "OutputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}",
  "ConsoleTheme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
  "RetainedFileCountLimit": "30",
  "FileSizeLimitBytes": "262144000",
  "RollOnFileSizeLimit": "true",
  "RollingInterval": "3"
}`

Builder:

       `public static Logger InitializeLogger()
        {
            var test1 = ConfigBuilder.BuildConfig();

            var logger = new LoggerConfiguration()
                .WriteTo.Async(x => x.File(
                    test1.Path,
                    test1.MinimumLevel,
                    test1.OutputTemplate,
                    null,
                    test1.FileSizeLimitBytes,
                    null,
                    false,
                    true,
                    null,
                    test1.RollingInterval,
                    test1.RollOnFileSizeLimit,
                    test1.RetainedFileCountLimit,
                    null,
                    null))
                .CreateLogger();

            return logger;
        }`

The implementation itself is very simple as I'm only trying to test the output for now:

       `static void Main(string[] args)
        {
            List<string> test = new List<string>();

            try
            {
                Console.WriteLine(test[0]);
            }
            catch (Exception ex)
            {
                SyncContext.Logger.Error($"{ex}");
                SyncContext.Logger.Information($"{ex}");
                SyncContext.Logger.Debug($"{ex}");
            }

            SyncContext.Logger.Error("Testing Implementation");
            Console.ReadKey();
        }`

**Comment by nblumhardt** [comment]
Hi! I'd guess there's some race condition or synchronization problem around `Console` somewhere in the picture. Try disposing the `Logger` (or calling `Log.CloseAndFlush()`, if you initialize the static `Log` class, before `Console.ReadKey()`. HTH!

**Comment by Pcardoso89** [comment]
Thank you @nblumhardt !

logger.Dispose() seems to work in firing off the queued jobs and I can now see the output successfully. I'm pretty sure I had tried this before but I must've done something wrong at the time.

Really appreciate the help!

**Comment by nblumhardt** [comment]
Thanks for the reply, glad that fixed it!
