### ISSUE TITLE
Unable to open file even after adding shared attribute

### ISSUE THREAD

**Issue by abhishek-v-github** [serilog/serilog-sinks-async#61]
.NetCore 3.1 -  File cannot be opened after staring a application.
Error: File cannot be used because it is being used by another process.

loggerFactory.AddSerilog();
            Log.Logger = new LoggerConfiguration().MinimumLevel.Information()
                .WriteTo.Async( o => o.File("test1.txt", shared: true)).CreateLogger();
            app.UseSerilogRequestLogging();

**Comment by chtenb** [comment]
That means that another handle to that file has been opened with exclusive permissions. The `shared` flag doesn't allow to bypass OS-level restrictions, it merely ensures that the logger itself doesn't acquire and exclusive lock. Does this only occur when using the Async sink? I would expect not.
