### ISSUE TITLE
Events do not flush on application exit if the logger is not the global logger

### ISSUE THREAD

**Issue by apenni** [serilog/serilog-sinks-async#62]
If creating a non-global logger (e.g. create an ILogger from a configuration, but do not assign it to Serilog.Log.Logger) then the application does not wait for the async log events to be written.

assigning the logger to Serilog.Log.Logger avoids the issue (when calling CloseAndFlush), but this is not ideal because there are use cases where you want async logging _not_ through the global logger.

**Comment by nblumhardt** [comment]
Hi @apenni,

The return value of `LoggerConfiguration.CreateLogger()` is the concrete `Logger` type (not `ILogger`), and this type implements `IDisposable` - disposing the logger will (should :-) ) flush all events.

HTH!

**Comment by apenni** [comment]
bingo! thanks. yep I was only storing the result as ILogger which doesn't have dispose
