### ISSUE TITLE
Routing log events by event type to be queued or not

### ISSUE THREAD

**Issue by sfiodorov** [serilog/serilog-sinks-async#78]
Hi.
Im using Redis sync to transfer app logs to elastic.
When using your wonderful nuget there is a chance when a fatal exception has happened and the process crashed (like OutOfMemory) but the log entry has not been processed yet since it was queued and it was additional logs to process before that.
My idea is to send fatal and error messages via regular Redis sync and less important messages via Async. The order is not important since the target organizes the logs by log datetime field.
So I prepared something like this:

```
 bool IsLogEventCritical(LogEvent logEvent) => logEvent.Level < LogEventLevel.Information;
                loggerConfiguration
                    // route non critical logs directly to queue before redis
                    .WriteTo
                    .Async(configureAsync =>
                        configureAsync.Conditional(x => !IsLogEventCritical(x),
                            loggerRedisAsyncConfiguration => loggerRedisAsyncConfiguration.Redis(redisConnectionConfig)))
                    // route critical logs directly to redis
                    .WriteTo
                    .Conditional(IsLogEventCritical,
                        loggerRedisConfiguration => loggerRedisConfiguration.Redis(redisConnectionConfig));
```
Is this a good practice to ensure that critical logs are delivered in case of application crash or not rejected from queue because of queue limit is reached?

**Comment by nblumhardt** [comment]
This looks fine to me, thanks for posting the example, hope it worked well for you! 👍
