### ISSUE TITLE
HealthMonitor full example

### ISSUE THREAD

**Issue by alex0598** [serilog/serilog-sinks-async#79]
Hi is there an example of the HealthMonitor for C# ?

**Comment by bartelink** [comment]
No, there is no complete sample (I wrote some code in the context of a larger system, but it was closed source)
There are tests in this repo that cover some of the config wiring, but their aim is not to illustrate something like that - they are focused on proving that the right calls happen at the right time, and to prove that blocking and/or dropping works as specified.

**Comment by raheinz57** [comment]
The monitor implementation can be configured using a Serilog hook in appsettings.json. I have uploaded an implementation that loads the monitor via appsettings.json
[AsyncMonitorHook.zip](https://github.com/serilog/serilog-sinks-async/files/11366631/AsyncMonitorHook.zip)
