### ISSUE TITLE
Async vs Parallel

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-async#8]
There are a couple of competing priorities to account for, and perhaps making those explicit will lead to a clearer design here?

 * **Async** - the goal is to minimize latency of `Log.*()` calls in the application by cheaply adding events to a (hopefully wait-free) queue and doing slower sink operations (e.g. file I/O) on a background thread
 * **Parallel** - the goal is to maximize throughput by fanning out slow sink operations to multiple worker threads (with similar low-latency needs at the application-side)

Is this correct? And if so, would it be correct to categorize the dataflow-based implementation as serving the second scenario better than the first?

(I came around to thinking about this because providing, say `WriteTo.Async()` as well as `WriteTo.Parallel()` could make the trade-offs easier to balance. A good parallel implementation seems likely to be more complex and have more overhead than the simpler async implementation.)

**Comment by jezzsantos** [comment]
I agree that those goals define the needs.

What I don't really know, is if the current implementation `BufferBlock<T>` + `ActionBlock<T>` only addresses one or other of these design goals.

I understand it buffers, and then async blocks calling thread. Not sure what else can be done in the same process?

I also understand that there is limited parallelism build into the Blocks. Not sure how we could optimize that though. We kind of need an expert with more experience in TPL to advise us.

**Comment by nblumhardt** [comment]
Dataflow can definitely serve both goals, it just won't be as efficent (nor as quick to flush/shut down) as a single dedicated worker thread pulling from a queue - many fewer moving parts required for the `Async()` case than the `Parallel()` one I think.

The one implementation could serve both goals - but if we separated them it may be easier to optimise for each separately. Just thought it'd be an interesting strategy to consider, anyway.

Perhaps I should spike up the complimentary approach so we can run some quick comparisons?

Also, I'm working from the assumption that this could eventually be _the_ async solution for Serilog, so I'm thinking ahead around performance etc. to a degree that might be overkill at this early stage. Hope I'm not derailing things too much :smile: 

Cheers!

**Comment by jezzsantos** [comment]
Sounds good. No danger of derailing anything.

**Comment by nblumhardt** [comment]
Hi Jezz,

Just checking in - what are your thoughts on where we are headed with this one?

Interestingly, the ASP.NET Team just wrote a version of this as well, at:

https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics/Internal/BackgroundSink.cs

I'd like to move forward and start bedding down the approach a bit. Are you keen to push forward with the TPL Dataflow version, or do you want to move towards the worker-thread option? I'm keen to develop the worker-thread approach further, but we could do both by splitting the package in two if that would work better for you. Thoughts?

Cheers!
Nick

**Comment by jezzsantos** [comment]
Hey Nick,

Honestly, I would be happy if you were to take this in what ever direction you think is right. You have the best context for this. 

The only evidence I ever had of TPL over WT-option is based upon work Stephen Cleary did, and his guidance around that. He advised that TPL (BufferBlock<T>) was the preferred option over BlockingCollecton<T> as it is apparently a more robust and better supported implementation. YMVM. 
 
You know best what to do in the general cases of Serilog though, and you hold the larger context of the more general use cases. You have clearly been thinking about this longer and the trade offs. . I just don't have a strong enough view, or experience enough with to take lead either way at this stage.

I'd be happy transfering over the repo to you if you prefer? I am probably not going to take it much further in the near term.

**Comment by nblumhardt** [comment]
Hey Jezz, sounds good. I'm still experimenting a little, so not sure exactly where it would land, but transferring it through to `serilog` and starting to iterate there would be awesome. I prefer the smaller code size/limited dependencies of the `BlockingCollection` approach, but with some time in the wild we might learn a bit more.

Here's one possible plan of attack:

 * Add `serilog` as a package owner on NuGet (Jezz)
 * Transfer repository to `nblumhardt` (so that I can add it to `serilog`) (Jezz)
 * Transfer to `serilog` (Nick)
 * Create a maintainers team for the repo and add Jezz, Nick (Nick)
 * Pare it back to the one `BlockingCollection` implementation (Nick)
 * Move to the standard Serilog build/test scripts and target .NET Core (Nick)
 * Turn on an AppVeyor build and get publishing happening (Nick)
 * Iterate :-)

Sounds like a plan?

**Comment by jezzsantos** [comment]
Done deal! On it shortly

**Comment by jezzsantos** [comment]
NuGet package owner - Done
Unable to transfer githug repo. "nblumhardt/Serilog.Sinks.Async already exists" - Nick,you need to delete your fork of this repo first.

**Comment by nblumhardt** [comment]
Deleted and ready to go, thanks Jezz

**Comment by jezzsantos** [comment]
Transfer to nblumhardt/Serilog.Sinks.Async - Done

I think that's it right?

**Comment by nblumhardt** [comment]
Done, thanks Jezz! I'll work through the next few steps later today and keep you posted :+1:

**Comment by nblumhardt** [comment]
@jezzsantos I've moved the checklist to https://github.com/serilog/serilog-sinks-async/issues/10 so it's a bit easier to follow. Should take me a couple of days to work through (optimism showing :smile:). Cheers!
