### ISSUE TITLE
Support for .NET Core version

### ISSUE THREAD

**Issue by djpentz** [serilog/serilog-sinks-async#87]
I may be mistaken but it seems like this library only support .NET Framework? I'm trying to use it from within a .NET Core app using paket, and it does not load.

If so, are there any plans to support .NET core or are the async issues not a problem with .NET core?

**Comment by SimonCropp** [comment]
it supports netcore via supporting netstandard 

![image](https://github.com/serilog/serilog-sinks-async/assets/122666/de33b334-5cd9-40a1-b911-78039794e4c2)
